name: behavioural-cloning
channels:
  - https://conda.anaconda.org/menpo
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - python-dotenv

  # Server packages
  - uvicorn
  - eventlet
  - flask-socketio

  # Model packages
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - h5py
  
  # Pip dependencies
  - pip:
      - fastapi
      - moviepy
      - tensorflow
      - keras